name: Run Pytest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run Pytest
      id: pytest
      run: |
        pytest

#    - name: Calculate Test Ratios
#      run: |
#        python -c "
#import json
#with open('report.json') as f:
#    report = json.load(f)
#modules = {}
#for test in report['tests']:
#    module = test['nodeid'].split('::')[0]
#    if module not in modules:
#        modules[module] = {'passed': 0, 'failed': 0}
#    if test['outcome'] == 'passed':
#        modules[module]['passed'] += 1
#    else:
#        modules[module]['failed'] += 1
#for module, results in modules.items():
#    total = results['passed'] + results['failed']
#    ratio = results['passed'] / total if total > 0 else 0
#    print(f'{module}: {results["passed"]}/{total} tests passed ({ratio:.2%})')
#        "