name: Run Pytest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -e .

      - name: Run pytest with coverage
        run: pytest

      - name: Update README
        run: |
          # Remplace la section progression dans README.md
          sed -i '/<!-- START_PROGRESS -->/,/<!-- END_PROGRESS -->/{
              /<!-- START_PROGRESS -->/{
                  p
                  r progress.md
              }
              /<!-- END_PROGRESS -->/p
              d
          }' README.md
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update test progress [skip ci]" || echo "Pas de changement"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
