name: Run Pytest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -e .

      - name: Run pytest with coverage
        run: pytest
        continue-on-error: true

      - name: generate report
        run: python generate-progress-report.py

      - name: Update README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update progress bars"
          file_pattern: README.md
          branch: main
